// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pavwvebdyemjgejkmfyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhdnd2ZWJkeWVtamdlamttZnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTUzNTgsImV4cCI6MjA3MTI5MTM1OH0.O3zjFL-1BPV20gQwHJnohA3B5fHMz7Srkl5uruybVTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});